services:
  mypf_be:
    build:
      context: .
      dockerfile: MyPortfolio/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mypf_db

  mypf_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: franco
      POSTGRES_PASSWORD: PasswordPostgreSQL
      POSTGRES_DB: MyPortfolio_DataDocker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  mypf_pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - mypf_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      
#  mypf_fe:
#    build:
#      context: ../MyBadPortfolioSite  # Path dove si trova il Dockerfile del FE
#      dockerfile: Dockerfile
#    ports:
#      - "4200:80"  # 4200 per convenzione FE Angular, esposto da NGINX su 80
#    depends_on:
#      - mypf_be  # Il FE dipende dal BE
#    restart: always  # Riavvia automaticamente in caso di errori
      

      

volumes:
  pgdata:
  pgadmin_data:
  