services:
  mypf_be:
    build:
      context: .
      dockerfile: MyPortfolio/Dockerfile
    ports:
      - "8080:8080"
#   depends_on:
#     - mypf_db
    environment:
     - ConnectionStrings__DataDBConnection=Host=192.168.1.154;Database=MyPortfolioTest;Username=frankborty;Password=tmac90
     - ConnectionStrings__StockPriceWatcherURL=http://192.168.1.150:50000/stock
 
  mypf_fe:
    build:
      context: ../MyPortfolioFE  # Path dove si trova il Dockerfile del FE
      dockerfile: Dockerfile
    ports:
      - "4200:80"  # 4200 per convenzione FE Angular, esposto da NGINX su 80
    depends_on:
      - mypf_be  # Il FE dipende dal BE
    restart: always  # Riavvia automaticamente in caso di errori
      

volumes:
  pgdata:
  pgadmin_data:
  